{"name": "test_login_failure[wrong_user-secret_sauce-Username and password do not match]", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидалась ошибка: Username and password do not match\nassert 'Username and password do not match' in ''", "trace": "driver = <undetected_chromedriver.Chrome (session=\"03ad0d04002dbbedd80c1ccc66130694\")>, username = 'wrong_user', password = 'secret_sauce', expected_error_message = 'Username and password do not match'\n\n    @allure.story(\"Негативные тесты\")\n    @allure.story(\"Негативные тесты авторизации\")\n    @pytest.mark.parametrize(\n        \"username, password, expected_error_message\",\n        [\n            (\"standard_user\", \"wrong_password\", \"Username and password do not match\"),\n            (\"wrong_user\", \"secret_sauce\", \"Username and password do not match\"),\n            (\"\", \"\", \"Username is required\"),\n        ]\n    )\n    def test_login_failure(driver, username, password, expected_error_message):\n        with allure.step(\"Открываем страницу авторизации\"):\n            login_page = LogPage(driver)\n            login_page.open(URL)\n    \n        with allure.step(f\"Выполняем вход с параметрами: username={username}, password{password}\"):\n            login_page.enter_username(username)\n            login_page.enter_password(password)\n    \n        with allure.step(\"Проверяем сообщение об ошибке\"):\n            error_message = login_page.get_error_message()\n>           assert expected_error_message in error_message, f\"Ожидалась ошибка: {expected_error_message}\"\nE           AssertionError: Ожидалась ошибка: Username and password do not match\nE           assert 'Username and password do not match' in ''\n\ntests/test_login_page.py:49: AssertionError"}, "steps": [{"name": "Открываем страницу авторизации", "status": "passed", "start": 1733932411340, "stop": 1733932411530}, {"name": "Выполняем вход с параметрами: username=wrong_user, passwordsecret_sauce", "status": "passed", "start": 1733932411531, "stop": 1733932411941}, {"name": "Проверяем сообщение об ошибке", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидалась ошибка: Username and password do not match\nassert 'Username and password do not match' in ''\n", "trace": "  File \"/media/grifftih/Linux/TestCases/SwagLabs/tests/test_login_page.py\", line 49, in test_login_failure\n    assert expected_error_message in error_message, f\"Ожидалась ошибка: {expected_error_message}\"\n"}, "start": 1733932411942, "stop": 1733932412004}], "parameters": [{"name": "username", "value": "'wrong_user'"}, {"name": "password", "value": "'secret_sauce'"}, {"name": "expected_error_message", "value": "'Username and password do not match'"}], "start": 1733932411339, "stop": 1733932412005, "uuid": "6079e3f9-68f1-4306-8397-70f98564dc6b", "historyId": "a4a25a3743fe3ed04ee1daeb70783d39", "testCaseId": "75bc51d029e4608920585d699e2de0b6", "fullName": "tests.test_login_page#test_login_failure", "labels": [{"name": "story", "value": "Негативные тесты"}, {"name": "story", "value": "Негативные тесты авторизации"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "griffith"}, {"name": "thread", "value": "14710-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_page"}]}