{"name": "test_login_failure[--Username is required]", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидалась ошибка: Username is required\nassert 'Username is required' in ''", "trace": "driver = <undetected_chromedriver.Chrome (session=\"03ad0d04002dbbedd80c1ccc66130694\")>, username = '', password = '', expected_error_message = 'Username is required'\n\n    @allure.story(\"Негативные тесты\")\n    @allure.story(\"Негативные тесты авторизации\")\n    @pytest.mark.parametrize(\n        \"username, password, expected_error_message\",\n        [\n            (\"standard_user\", \"wrong_password\", \"Username and password do not match\"),\n            (\"wrong_user\", \"secret_sauce\", \"Username and password do not match\"),\n            (\"\", \"\", \"Username is required\"),\n        ]\n    )\n    def test_login_failure(driver, username, password, expected_error_message):\n        with allure.step(\"Открываем страницу авторизации\"):\n            login_page = LogPage(driver)\n            login_page.open(URL)\n    \n        with allure.step(f\"Выполняем вход с параметрами: username={username}, password{password}\"):\n            login_page.enter_username(username)\n            login_page.enter_password(password)\n    \n        with allure.step(\"Проверяем сообщение об ошибке\"):\n            error_message = login_page.get_error_message()\n>           assert expected_error_message in error_message, f\"Ожидалась ошибка: {expected_error_message}\"\nE           AssertionError: Ожидалась ошибка: Username is required\nE           assert 'Username is required' in ''\n\ntests/test_login_page.py:49: AssertionError"}, "steps": [{"name": "Открываем страницу авторизации", "status": "passed", "start": 1733932412027, "stop": 1733932412221}, {"name": "Выполняем вход с параметрами: username=, password", "status": "passed", "start": 1733932412221, "stop": 1733932412619}, {"name": "Проверяем сообщение об ошибке", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидалась ошибка: Username is required\nassert 'Username is required' in ''\n", "trace": "  File \"/media/grifftih/Linux/TestCases/SwagLabs/tests/test_login_page.py\", line 49, in test_login_failure\n    assert expected_error_message in error_message, f\"Ожидалась ошибка: {expected_error_message}\"\n"}, "start": 1733932412619, "stop": 1733932412679}], "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "''"}, {"name": "expected_error_message", "value": "'Username is required'"}], "start": 1733932412027, "stop": 1733932412680, "uuid": "57a5c708-bd2b-48e4-97cd-90742efa47b5", "historyId": "4112a93a466173afad6e61aaf5588f69", "testCaseId": "75bc51d029e4608920585d699e2de0b6", "fullName": "tests.test_login_page#test_login_failure", "labels": [{"name": "story", "value": "Негативные тесты"}, {"name": "story", "value": "Негативные тесты авторизации"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "griffith"}, {"name": "thread", "value": "14710-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_page"}]}